version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tordilla-web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@postgres:5432/${DB_NAME}

    PORT: "3000"
    restart: unless-stopped
